## 106 - ISEP Workplace Sexism


```
- sexist and ambiguous or neutral sentences, manually built and annotated: 1/0
  – 55% - A manually filtered subset of a Twitter hate speech dataset created by [dataset 34]
  – 25% - A manually filtered subset of work-related quotes
  – 20% - Miscellaneous press quotes and faculty/student submissions

- Dataset Size: `1137`, manually annotated
- Input format: `text,label`
- Output format: `id,text,label`
```

```
label:
- 0: not biased
- 1: biased
```

In [1]:
import os
import sys
import pandas as pd
from prep_collection import PrepCollection as prep

In [2]:
path_input_relative = "/Datasets/Gender Bias/106-workplace-sexism/ISEP Sexist Data labeling.xlsx"
path_output_relative = "/Preprocessed_Datasets/106-workplacesexism.csv"

In [3]:
wdr_path = os.path.dirname(os.path.dirname(os.getcwd()))
df = pd.read_excel(os.path.join(wdr_path + path_input_relative))

df['id'] = pd.DataFrame(range(len(df))) + 1
df['text'] = df['Sentences']
df['text'] = df['text'].apply(str).apply(prep.prepare_text)

df['label'] = df['Label']

df = df.reindex(columns=['id','text','label'])
df

        id                                               text  label
0        1                           For a woman that is good      1
1        2    Just dress sexy and you will sign any contract       1
2        3                             Are you having period       1
3        4                                  Stop being bitchy      1
4        5  I leave early because of her children instead ...      1
...    ...                                                ...    ...
1132  1133  Opportunities are like night owls They like to...      0
1133  1134  It s not just a question of doing what you lov...      0
1134  1135  A genius does what he masters An ordinary man ...      0
1135  1136  If you want to know the real reasons behind th...      0
1136  1137  Questioning is important for breakthrough inno...      0

[1137 rows x 3 columns]

In [4]:
df.to_csv(wdr_path + path_output_relative)